### PR TITLE
New paragraph added by SS

### PR DESCRIPTION
**Pull request by skipstevenson**
Added a new paragraph

### CODE REVIEW

**Comment by robertovormittag** [comment]
Hi, can you describe briefly the problem here?

**Comment by skipstevenson** [comment]
Hi,
Thanks for responding.

This Pastebin link describes it in detail.  www.pastebin.com/jH0Lvzz6


I subsequently tried an alternative command to add the local repo to
github:

git remote set-url origin https://github.com/
<my-github-username>/testrepo.git

On Thu, Aug 9, 2018 at 10:23 AM, Roberto Vormittag <notifications@github.com

**Comment by skipstevenson** [comment]
Hi Roberto,

I posted this question on a few facebook groups as well.  A couple of
people mentioned that the git command   $ git remote add origin
https://github.com/<my-github-username>/testrepo  is simply defining a URL
for origin, but that you have to go to your github account to actually
create the repo there, before you can push to it.

Does that sound correct to you?  I didn't see that step in your book.

Thanks again,

Skip Stevenson


On Thu, Aug 9, 2018 at 10:23 AM, Roberto Vormittag <notifications@github.com

**Comment by robertovormittag** [comment]
Hi, yes that's correct (apologies for the late reply)

**Pull request closed without merging**
