### PR TITLE
New paragraph added

### PR DESCRIPTION
**Pull request by MaGitKo**
Thank you Robert for this excellent book!

### CODE REVIEW

**Comment by MaGitKo** [comment]
# Comment
This is just a test comment.

**Comment by robertovormittag** [comment]
> Thank you Robert for this excellent book!

**Comment by robertovormittag** [comment]
Hello and Welcome to GitHub! Thank you for contributing to this project, your change has been merged.
Best wishes,
Roberto

**Comment by robertovormittag** [comment]
> Thank you Robert for this excellent book!

You are very welcome :)

**Pull request merged**
